# Generated by Django 4.1.1 on 2023-05-07 12:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import users.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("email", models.EmailField(max_length=255, unique=True)),
                (
                    "register_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "role",
                    models.CharField(
                        choices=[("artist", "artist"), ("company", "company")],
                        max_length=30,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CompanySoftware",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photoshop", models.BooleanField(default=False)),
                ("afterEffects", models.BooleanField(default=False)),
                ("premiere", models.BooleanField(default=False)),
                ("substancePainter", models.BooleanField(default=False)),
                ("substanceDesigner", models.BooleanField(default=False)),
                ("lightroom", models.BooleanField(default=False)),
                ("Coat", models.BooleanField(default=False)),
                ("max", models.BooleanField(default=False)),
                ("affinityDesigner", models.BooleanField(default=False)),
                ("affinityPhoto", models.BooleanField(default=False)),
                ("akeytsu", models.BooleanField(default=False)),
                ("Arnold", models.BooleanField(default=False)),
                ("blender", models.BooleanField(default=False)),
                ("cinema4d", models.BooleanField(default=False)),
                ("clarisseIfx", models.BooleanField(default=False)),
                ("clipStudioPaint", models.BooleanField(default=False)),
                ("corelpainter", models.BooleanField(default=False)),
                ("dazStudio", models.BooleanField(default=False)),
                ("gaea", models.BooleanField(default=False)),
                ("gimp", models.BooleanField(default=False)),
                ("gravitySketch", models.BooleanField(default=False)),
                ("houdini", models.BooleanField(default=False)),
                ("illustrator", models.BooleanField(default=False)),
                ("infinitePainter", models.BooleanField(default=False)),
                ("keyshot", models.BooleanField(default=False)),
                ("krita", models.BooleanField(default=False)),
                ("mangaStudio", models.BooleanField(default=False)),
                ("mari", models.BooleanField(default=False)),
                ("marmoset", models.BooleanField(default=False)),
                ("marvelousDesigner", models.BooleanField(default=False)),
                ("maya", models.BooleanField(default=False)),
                ("mentalRay", models.BooleanField(default=False)),
                ("moi3d", models.BooleanField(default=False)),
                ("modo", models.BooleanField(default=False)),
                ("mudbox", models.BooleanField(default=False)),
                ("nuke", models.BooleanField(default=False)),
                ("paintToolSai", models.BooleanField(default=False)),
                ("procreate", models.BooleanField(default=False)),
                ("quixelSuite", models.BooleanField(default=False)),
                ("revit", models.BooleanField(default=False)),
                ("rhino", models.BooleanField(default=False)),
                ("sketchbookPro", models.BooleanField(default=False)),
                ("sketchup", models.BooleanField(default=False)),
                ("speedtree", models.BooleanField(default=False)),
                ("terragen", models.BooleanField(default=False)),
                ("unity", models.BooleanField(default=False)),
                ("unrealEngine", models.BooleanField(default=False)),
                ("vray", models.BooleanField(default=False)),
                ("zbrush", models.BooleanField(default=False)),
                ("xnormal", models.BooleanField(default=False)),
                ("davinci", models.BooleanField(default=False)),
                ("resolve", models.BooleanField(default=False)),
                ("octaneRender", models.BooleanField(default=False)),
                ("redshift", models.BooleanField(default=False)),
                ("flame", models.BooleanField(default=False)),
                ("fusion", models.BooleanField(default=False)),
                ("natron", models.BooleanField(default=False)),
                ("meshlab", models.BooleanField(default=False)),
                ("meshroom", models.BooleanField(default=False)),
                ("pftrack", models.BooleanField(default=False)),
                ("equalizer", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompanySocialMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("portfolio", models.URLField(blank=True, max_length=255)),
                ("youtube", models.URLField(blank=True, max_length=255)),
                ("linkedin", models.URLField(blank=True, max_length=255)),
                ("instagram", models.URLField(blank=True, max_length=255)),
                ("github", models.URLField(blank=True, max_length=255)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompanySector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("luxury", models.BooleanField(default=False)),
                ("vfx", models.BooleanField(default=False)),
                ("video games", models.BooleanField(default=False)),
                ("motion", models.BooleanField(default=False)),
                ("design", models.BooleanField(default=False)),
                ("architecture", models.BooleanField(default=False)),
                ("animation", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompanyMobility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full remote", models.BooleanField(default=False)),
                ("hybrid", models.BooleanField(default=False)),
                ("on site", models.BooleanField(default=False)),
                ("Relocation Assistance", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompanyIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        default="logos/company_default.png",
                        upload_to="logos",
                        validators=[
                            users.validators.validate_file_size,
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png"]
                            ),
                        ],
                    ),
                ),
                ("company_name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "company_size",
                    models.CharField(
                        choices=[
                            ("1 - 10", "1 - 10"),
                            ("11 - 50", "11 - 50"),
                            ("51 - 99", "51 - 99"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompanyCoordinate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(blank=True, max_length=60)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=255)),
                ("zip_code", models.CharField(blank=True, max_length=10)),
                ("street_name", models.CharField(blank=True, max_length=100)),
                ("street_number", models.CharField(blank=True, max_length=10)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompanyContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full-time", models.BooleanField(default=False)),
                ("part-time", models.BooleanField(default=False)),
                ("freelance", models.BooleanField(default=False)),
                ("Internship", models.BooleanField(default=False)),
                ("apprenticeship", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompanyCompetence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("generalist", models.BooleanField(default=False)),
                ("conceptart", models.BooleanField(default=False)),
                ("match_moving", models.BooleanField(default=False)),
                ("modeling", models.BooleanField(default=False)),
                ("rigging", models.BooleanField(default=False)),
                ("animating", models.BooleanField(default=False)),
                ("texturing", models.BooleanField(default=False)),
                ("surfacing", models.BooleanField(default=False)),
                ("rendering", models.BooleanField(default=False)),
                ("compositing", models.BooleanField(default=False)),
                ("rotoscopy", models.BooleanField(default=False)),
                ("video_editing", models.BooleanField(default=False)),
                ("motionDesign", models.BooleanField(default=False)),
                ("technical_director", models.BooleanField(default=False)),
                ("developer", models.BooleanField(default=False)),
                ("production_manager", models.BooleanField(default=False)),
                ("producer", models.BooleanField(default=False)),
                ("coordinator", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArtistSoftware",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photoshop",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "afterEffects",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "premiere",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "substancePainter",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "substanceDesigner",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "lightroom",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "Coat",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "max",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "affinityDesigner",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "affinityPhoto",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "akeytsu",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "Arnold",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "blender",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "cinema4d",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "clarisseIfx",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "clipStudioPaint",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "corelpainter",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "dazStudio",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "gaea",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "gimp",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "gravitySketch",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "houdini",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "illustrator",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "infinitePainter",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "keyshot",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "krita",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "mangaStudio",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "mari",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "marmoset",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "marvelousDesigner",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "maya",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "mentalRay",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "moi3d",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "modo",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "mudbox",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "nuke",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "paintToolSai",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "procreate",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "quixelSuite",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "revit",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "rhino",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "sketchbookPro",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "sketchup",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "speedtree",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "terragen",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "unity",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "unrealEngine",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "vray",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "zbrush",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "xnormal",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "davinci",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "resolve",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "octaneRender",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "redshift",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "flame",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "fusion",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "natron",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "meshlab",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "meshroom",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "pftrack",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "equalizer",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArtistSocialMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("portfolio", models.URLField(blank=True, max_length=255)),
                ("youtube", models.URLField(blank=True, max_length=255)),
                ("linkedin", models.URLField(blank=True, max_length=255)),
                ("instagram", models.URLField(blank=True, max_length=255)),
                ("github", models.URLField(blank=True, max_length=255)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArtistSector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("luxury", models.BooleanField(default=False)),
                ("vfx", models.BooleanField(default=False)),
                ("video games", models.BooleanField(default=False)),
                ("motion", models.BooleanField(default=False)),
                ("design", models.BooleanField(default=False)),
                ("architecture", models.BooleanField(default=False)),
                ("animation", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArtistMobility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full remote", models.BooleanField(default=False)),
                ("hybrid", models.BooleanField(default=False)),
                ("on site", models.BooleanField(default=False)),
                ("Relocation Assistance", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArtistIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        default="avatars/artist_default.png",
                        upload_to="avatars",
                        validators=[
                            users.validators.validate_file_size,
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png"]
                            ),
                        ],
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=50)),
                ("first_name", models.CharField(blank=True, max_length=255)),
                ("last_name", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArtistCoordinate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(blank=True, max_length=60)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=255)),
                ("zip_code", models.CharField(blank=True, max_length=10)),
                ("street_name", models.CharField(blank=True, max_length=100)),
                ("street_number", models.CharField(blank=True, max_length=10)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArtistContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full-time", models.BooleanField(default=False)),
                ("part-time", models.BooleanField(default=False)),
                ("freelance", models.BooleanField(default=False)),
                ("Internship", models.BooleanField(default=False)),
                ("apprenticeship", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArtistCompetence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "generalist",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "conceptart",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "match_moving",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "modeling",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "rigging",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "animating",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "texturing",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "surfacing",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "rendering",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "compositing",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "rotoscopy",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "video_editing",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "motionDesign",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "technical_director",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "developer",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "production_manager",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "producer",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "coordinator",
                    models.CharField(
                        choices=[
                            ("Never practiced", "1 - Never practiced"),
                            ("Novice", "2 - Novice"),
                            ("Advanced Beginner", "3 - Advanced, Beginner"),
                            ("Competent", "4 - Competent"),
                            ("Proficient", "5 - Proficient"),
                            ("Expert", "6 - Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArtistAdministrative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spectacle_number", models.CharField(blank=True, max_length=10)),
                ("siret_number", models.CharField(blank=True, max_length=14)),
                ("price", models.CharField(blank=True, max_length=5)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
