def get_profile_data(user):
    context = {}
    context['identity'] = {
        'avatar': user.artist.avatar,
        'first_name': user.artist.first_name,
        'last_name': user.artist.last_name,
        'title': user.artist.title,
        'description': user.artist.description
    }
    context['coordonates'] = {
        'email': user.email,
        'phone': user.phone_number,
        'city': user.city,
        'state': user.state,
        'zip_code': user.zip_code,
        'country': user.country,
        }
    context['contracts'] = {
        'cdd': user.artist.cdd,
        'cdi': user.artist.cdi,
        'stage': user.artist.stage,
        'freelance': user.artist.freelance,
        'intermittent': user.artist.intermittent,
        'alternate': user.artist.alternate
        }
    context['artistic_skills'] = {'generalist': user.artist.generalist,
                                  'conceptart': user.artist.conceptart,
                                  'match_moving': user.artist.match_moving,
                                  'modeling': user.artist.modeling,
                                  'rigging': user.artist.rigging,
                                  'animating': user.artist.animating,
                                  'texturing': user.artist.texturing,
                                  'surfacing': user.artist.surfacing,
                                  'rendering': user.artist.rendering,
                                  'compositing': user.artist.compositing,
                                  'video_editing': user.artist.video_editing,
                                  'motionDesign': user.artist.motionDesign,
                                  'technical_director': user.artist.technical_director,
                                  'developer': user.artist.developer,
                                  'production_manager': user.artist.production_manager,
                                  'productor': user.artist.productor,
                                  'coordinator': user.artist.coordinator
                                  }
    context['sectors'] = {'luxe': user.artist.luxe,
                          'vfx': user.artist.vfx,
                          'games': user.artist.games,
                          'motion': user.artist.motion,
                          'design': user.artist.design,
                          'architecture': user.artist.architecture,
                          'animation': user.artist.animation
                          }
    context['urls'] = {'website': user.artist.website,
                       'linkedin': user.artist.linkedin,
                       'youtube': user.artist.youtube,
                       'instagram': user.artist.instagram,
                       'github': user.artist.github
                       }
    context['softwares'] = {'photoshop': user.artist.photoshop,
                            'afterEffects': user.artist.afterEffects,
                            'premiere': user.artist.premiere,
                            'substancePainter': user.artist.substancePainter,
                            'substanceDesigner': user.artist.substanceDesigner,
                            'lightroom': user.artist.lightroom,
                            'Coat': user.artist.Coat,
                            'max': user.artist.max,
                            'affinityDesigner': user.artist.affinityDesigner,
                            'affinityPhoto': user.artist.affinityPhoto,
                            'akeytsu': user.artist.akeytsu,
                            'Arnold': user.artist.Arnold,
                            'blender': user.artist.blender,
                            'cinema4d': user.artist.cinema4d,
                            'clarisseIfx': user.artist.clarisseIfx,
                            'clipStudioPaint': user.artist.clipStudioPaint,
                            'corelpainter': user.artist.corelpainter,
                            'dazStudio': user.artist.dazStudio,
                            'gaea': user.artist.gaea,
                            'gimp': user.artist.gimp,
                            'gravitySketch': user.artist.gravitySketch,
                            'houdini': user.artist.houdini,
                            'illustrator': user.artist.illustrator,
                            'infinitePainter': user.artist.infinitePainter,
                            'keyshot': user.artist.keyshot,
                            'krita': user.artist.krita,
                            'mangaStudio': user.artist.mangaStudio,
                            'mari': user.artist.mari,
                            'marmoset': user.artist.marmoset,
                            'marvelousDesigner': user.artist.marvelousDesigner,
                            'maya': user.artist.maya,
                            'mentalRay': user.artist.mentalRay,
                            'moi3d': user.artist.moi3d,
                            'modo': user.artist.modo,
                            'mudbox': user.artist.mudbox,
                            'nuke': user.artist.nuke,
                            'paintToolSai': user.artist.paintToolSai,
                            'procreate': user.artist.procreate,
                            'quixelSuite': user.artist.quixelSuite,
                            'revit': user.artist.revit,
                            'rhino': user.artist.rhino,
                            'sketchbookPro': user.artist.sketchbookPro,
                            'sketchup': user.artist.sketchup,
                            'speedtree': user.artist.speedtree,
                            'terragen': user.artist.terragen,
                            'unity': user.artist.unity,
                            'unrealEngine': user.artist.unrealEngine,
                            'vray': user.artist.vray,
                            'zbrush': user.artist.zbrush,
                            'xnormal': user.artist.xnormal,
                            'davinci': user.artist.davinci,
                            'resolve': user.artist.resolve,
                            'octaneRender': user.artist.octaneRender,
                            'redshift': user.artist.redshift,
                            'flame': user.artist.flame,
                            'fusion': user.artist.fusion,
                            'natron': user.artist.natron,
                            'meshlab': user.artist.meshlab,
                            'meshroom': user.artist.meshroom,
                            'pftrack': user.artist.pftrack,
                            'equalizer': user.artist.equalizer
                            }
    return context


def get_job_data(job):
    context = {}
    context['identity'] = {'logo': job.logo,
                           'title': job.title,
                           'company_name': job.company_name,
                           'description': job.description,
                           'company_size': job.company_size,
                           'sector': job.sector,
                           'contract_type': job.contract_type,
                           'salary_min': job.salary_min,
                           'salary_max': job.salary_max
                        }

    context['artistic_skills'] = {'generalist': job.generalist,
                                  'conceptart': job.conceptart,
                                  'match_moving': job.match_moving,
                                  'modeling': job.modeling,
                                  'rigging': job.rigging,
                                  'animating': job.animating,
                                  'texturing': job.texturing,
                                  'surfacing': job.surfacing,
                                  'rendering': job.rendering,
                                  'compositing': job.compositing,
                                  'video_editing': job.video_editing,
                                  'motionDesign': job.motionDesign,
                                  'technical_director': job.technical_director,
                                  'developer': job.developer,
                                  'production_manager': job.production_manager,
                                  'productor': job.productor,
                                  'coordinator': job.coordinator
                                  }

    context['softwares'] = {'photoshop': job.photoshop,
                            'afterEffects': job.afterEffects,
                            'premiere': job.premiere,
                            'substancePainter': job.substancePainter,
                            'substanceDesigner': job.substanceDesigner,
                            'lightroom': job.lightroom,
                            'Coat': job.Coat,
                            'max': job.max,
                            'affinityDesigner': job.affinityDesigner,
                            'affinityPhoto': job.affinityPhoto,
                            'akeytsu': job.akeytsu,
                            'Arnold': job.Arnold,
                            'blender': job.blender,
                            'cinema4d': job.cinema4d,
                            'clarisseIfx': job.clarisseIfx,
                            'clipStudioPaint': job.clipStudioPaint,
                            'corelpainter': job.corelpainter,
                            'dazStudio': job.dazStudio,
                            'gaea': job.gaea,
                            'gimp': job.gimp,
                            'gravitySketch': job.gravitySketch,
                            'houdini': job.houdini,
                            'illustrator': job.illustrator,
                            'infinitePainter': job.infinitePainter,
                            'keyshot': job.keyshot,
                            'krita': job.krita,
                            'mangaStudio': job.mangaStudio,
                            'mari': job.mari,
                            'marmoset': job.marmoset,
                            'marvelousDesigner': job.marvelousDesigner,
                            'maya': job.maya,
                            'mentalRay': job.mentalRay,
                            'moi3d': job.moi3d,
                            'modo': job.modo,
                            'mudbox': job.mudbox,
                            'nuke': job.nuke,
                            'paintToolSai': job.paintToolSai,
                            'procreate': job.procreate,
                            'quixelSuite': job.quixelSuite,
                            'revit': job.revit,
                            'rhino': job.rhino,
                            'sketchbookPro': job.sketchbookPro,
                            'sketchup': job.sketchup,
                            'speedtree': job.speedtree,
                            'terragen': job.terragen,
                            'unity': job.unity,
                            'unrealEngine': job.unrealEngine,
                            'vray': job.vray,
                            'zbrush': job.zbrush,
                            'xnormal': job.xnormal,
                            'davinci': job.davinci,
                            'resolve': job.resolve,
                            'octaneRender': job.octaneRender,
                            'redshift': job.redshift,
                            'flame': job.flame,
                            'fusion': job.fusion,
                            'natron': job.natron,
                            'meshlab': job.meshlab,
                            'meshroom': job.meshroom,
                            'pftrack': job.pftrack,
                            'equalizer': job.equalizer
                            }
    return context


def get_company_data(company):
    context = {}
    context['identity'] = {'logo': company.logo,
                           'company_name': company.company_name,
                           'description': company.description,
                           'company_size': company.company_size,
                        }
    context['coordonates'] = {'email': company.user.email,
                              'phone': company.user.phone_number,
                              'country': company.user.country,
                              'state': company.user.state,
                              'city': company.user.city,
                              'zip_code': company.user.zip_code,
                              'street_name': company.user.street_name,
                              'street_number': company.user.street_number,
                              }
    context['urls'] = {'website': company.website}
    context['sectors'] = {'luxe': company.luxe,
                          'vfx': company.vfx,
                          'games': company.games,
                          'motion': company.motion,
                          'design': company.design,
                          'architecture': company.architecture,
                          'animation': company.animation,
                        }
    return context
