# Generated by Django 4.1.1 on 2023-04-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='description',
        ),
        migrations.AddField(
            model_name='job',
            name='company_description',
            field=models.TextField(default='Foreign Key (type determined by related field)'),
        ),
        migrations.AddField(
            model_name='job',
            name='employee_benefits',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='job',
            name='job_requirements',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='job',
            name='job_responsibilities',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='job',
            name='required_qualifications',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='job',
            name='required_skills',
            field=models.TextField(default=''),
        ),
    ]
