# Generated by Django 4.1.1 on 2023-05-08 13:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0002_job_owner_id_alter_job_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="owner_id",
        ),
    ]
