def get_profile_data(user):
    context = {}
    context['identity'] = {'logo': user.company.logo,
                           'company_name': user.company.company_name,
                           'description': user.company.description,
                           'company_size': user.company.company_size,
                           }
    context['coordonates'] = {'email': user.email,
                              'phone': user.phone_number,
                              'country': user.country,
                              'state': user.state,
                              'city': user.city,
                              'zip_code': user.zip_code,
                              'street_name': user.street_name,
                              'street_number': user.street_number,
                              }
    context['urls'] = {'website': user.company.website}
    context['sectors'] = {'luxe': user.company.luxe,
                          'vfx': user.company.vfx,
                          'games': user.company.games,
                          'motion': user.company.motion,
                          'design': user.company.design,
                          'architecture': user.company.architecture,
                          'animation': user.company.animation,
                          }
    return context


def get_artist_data(artist):
    context = {}
    context['identity'] = {'avatar': artist.avatar,
                           'first_name': artist.first_name,
                           'last_name': artist.last_name,
                           'description': artist.description
                            }
    context['coordonates'] = {'email': artist.user.email,
                              'phone': artist.user.phone_number,
                              'city': artist.user.city,
                              'state': artist.user.state,
                              'zip_code': artist.user.zip_code,
                              'country': artist.user.country,
                            }
    context['contracts'] = {'cdd': artist.cdd,
                            'cdi': artist.cdi,
                            'stage': artist.stage,
                            'freelance': artist.freelance,
                            'intermittent': artist.intermittent,
                            'alternate': artist.alternate
                            }
    context['artistic_skills'] = {'generalist': artist.generalist,
                                  'conceptart': artist.conceptart,
                                  'match_moving': artist.match_moving,
                                  'modeling': artist.modeling,
                                  'rigging': artist.rigging,
                                  'animating': artist.animating,
                                  'texturing': artist.texturing,
                                  'surfacing': artist.surfacing,
                                  'rendering': artist.rendering,
                                  'compositing': artist.compositing,
                                  'video_editing': artist.video_editing,
                                  'motionDesign': artist.motionDesign,
                                  'technical_director': artist.technical_director,
                                  'developer': artist.developer,
                                  'production_manager': artist.production_manager,
                                  'productor': artist.productor,
                                  'coordinator': artist.coordinator
    }
    context['sectors'] = {'luxe': artist.luxe,
                          'vfx': artist.vfx,
                          'games': artist.games,
                          'motion': artist.motion,
                          'design': artist.design,
                          'architecture': artist.architecture,
                          'animation': artist.animation
                          }
    context['urls'] = {'website': artist.website,
                       'linkedin': artist.linkedin,
                       'youtube': artist.youtube,
                       'instagram': artist.instagram,
                       'github': artist.github
                       }
    context['softwares'] = {'photoshop': artist.photoshop,
                            'afterEffects': artist.afterEffects,
                            'premiere': artist.premiere,
                            'substancePainter': artist.substancePainter,
                            'substanceDesigner': artist.substanceDesigner,
                            'lightroom': artist.lightroom,
                            'Coat': artist.Coat,
                            'max': artist.max,
                            'affinityDesigner': artist.affinityDesigner,
                            'affinityPhoto': artist.affinityPhoto,
                            'akeytsu': artist.akeytsu,
                            'Arnold': artist.Arnold,
                            'blender': artist.blender,
                            'cinema4d': artist.cinema4d,
                            'clarisseIfx': artist.clarisseIfx,
                            'clipStudioPaint': artist.clipStudioPaint,
                            'corelpainter': artist.corelpainter,
                            'dazStudio': artist.dazStudio,
                            'gaea': artist.gaea,
                            'gimp': artist.gimp,
                            'gravitySketch': artist.gravitySketch,
                            'houdini': artist.houdini,
                            'illustrator': artist.illustrator,
                            'infinitePainter': artist.infinitePainter,
                            'keyshot': artist.keyshot,
                            'krita': artist.krita,
                            'mangaStudio': artist.mangaStudio,
                            'mari': artist.mari,
                            'marmoset': artist.marmoset,
                            'marvelousDesigner': artist.marvelousDesigner,
                            'maya': artist.maya,
                            'mentalRay': artist.mentalRay,
                            'moi3d': artist.moi3d,
                            'modo': artist.modo,
                            'mudbox': artist.mudbox,
                            'nuke': artist.nuke,
                            'paintToolSai': artist.paintToolSai,
                            'procreate': artist.procreate,
                            'quixelSuite': artist.quixelSuite,
                            'revit': artist.revit,
                            'rhino': artist.rhino,
                            'sketchbookPro': artist.sketchbookPro,
                            'sketchup': artist.sketchup,
                            'speedtree': artist.speedtree,
                            'terragen': artist.terragen,
                            'unity': artist.unity,
                            'unrealEngine': artist.unrealEngine,
                            'vray': artist.vray,
                            'zbrush': artist.zbrush,
                            'xnormal': artist.xnormal,
                            'davinci': artist.davinci,
                            'resolve': artist.resolve,
                            'octaneRender': artist.octaneRender,
                            'redshift': artist.redshift,
                            'flame': artist.flame,
                            'fusion': artist.fusion,
                            'natron': artist.natron,
                            'meshlab': artist.meshlab,
                            'meshroom': artist.meshroom,
                            'pftrack': artist.pftrack,
                            'equalizer': artist.equalizer
                            }
    return context


def get_job_data(job):
    context = {}
    context['identity'] = {'logo': job.logo,
                           'title': job.title,
                           'company_name': job.company_name,
                           'description': job.description,
                           'company_size': job.company_size,
                           'sector': job.sector,
                           'contract_type': job.contract_type,
                           'salary_min': job.salary_min,
                           'salary_max': job.salary_max
                        }

    context['artistic_skills'] = {'generalist': job.generalist,
                                  'conceptart': job.conceptart,
                                  'match_moving': job.match_moving,
                                  'modeling': job.modeling,
                                  'rigging': job.rigging,
                                  'animating': job.animating,
                                  'texturing': job.texturing,
                                  'surfacing': job.surfacing,
                                  'rendering': job.rendering,
                                  'compositing': job.compositing,
                                  'video_editing': job.video_editing,
                                  'motionDesign': job.motionDesign,
                                  'technical_director': job.technical_director,
                                  'developer': job.developer,
                                  'production_manager': job.production_manager,
                                  'productor': job.productor,
                                  'coordinator': job.coordinator
                                  }

    context['softwares'] = {'photoshop': job.photoshop,
                            'afterEffects': job.afterEffects,
                            'premiere': job.premiere,
                            'substancePainter': job.substancePainter,
                            'substanceDesigner': job.substanceDesigner,
                            'lightroom': job.lightroom,
                            'Coat': job.Coat,
                            'max': job.max,
                            'affinityDesigner': job.affinityDesigner,
                            'affinityPhoto': job.affinityPhoto,
                            'akeytsu': job.akeytsu,
                            'Arnold': job.Arnold,
                            'blender': job.blender,
                            'cinema4d': job.cinema4d,
                            'clarisseIfx': job.clarisseIfx,
                            'clipStudioPaint': job.clipStudioPaint,
                            'corelpainter': job.corelpainter,
                            'dazStudio': job.dazStudio,
                            'gaea': job.gaea,
                            'gimp': job.gimp,
                            'gravitySketch': job.gravitySketch,
                            'houdini': job.houdini,
                            'illustrator': job.illustrator,
                            'infinitePainter': job.infinitePainter,
                            'keyshot': job.keyshot,
                            'krita': job.krita,
                            'mangaStudio': job.mangaStudio,
                            'mari': job.mari,
                            'marmoset': job.marmoset,
                            'marvelousDesigner': job.marvelousDesigner,
                            'maya': job.maya,
                            'mentalRay': job.mentalRay,
                            'moi3d': job.moi3d,
                            'modo': job.modo,
                            'mudbox': job.mudbox,
                            'nuke': job.nuke,
                            'paintToolSai': job.paintToolSai,
                            'procreate': job.procreate,
                            'quixelSuite': job.quixelSuite,
                            'revit': job.revit,
                            'rhino': job.rhino,
                            'sketchbookPro': job.sketchbookPro,
                            'sketchup': job.sketchup,
                            'speedtree': job.speedtree,
                            'terragen': job.terragen,
                            'unity': job.unity,
                            'unrealEngine': job.unrealEngine,
                            'vray': job.vray,
                            'zbrush': job.zbrush,
                            'xnormal': job.xnormal,
                            'davinci': job.davinci,
                            'resolve': job.resolve,
                            'octaneRender': job.octaneRender,
                            'redshift': job.redshift,
                            'flame': job.flame,
                            'fusion': job.fusion,
                            'natron': job.natron,
                            'meshlab': job.meshlab,
                            'meshroom': job.meshroom,
                            'pftrack': job.pftrack,
                            'equalizer': job.equalizer
                            }
    return context