# Generated by Django 4.1.1 on 2023-06-15 15:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comment", "0002_comment_post"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="author",
            new_name="user",
        ),
    ]
