# Generated by Django 4.1.1 on 2023-06-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comment", "0003_rename_author_comment_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
