# Generated by Django 4.1.1 on 2023-06-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comment", "0005_alter_comment_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_reply",
            field=models.BooleanField(default=False),
        ),
    ]
